server:
  port: 9001

grpc:
  enabled: true
  port: 9002

datasource:
  driverName: mysql
  host: 127.0.0.1
  port: 3306
  database: im
  username: root
  password: root
  charset: "utf8mb4"
  loc: Local
  tablePrefix: ""

redis:
  host: 192.168.0.88:6379
  db: 0
  password: lyh.123456

log:
  filePath: ./runtime/logs/
  fileName: system.log

cron:
  enabled: false

modelCache:
  key: '{mc:%s}:%s:%s'
  ttl: 1500
  emptyTTL: 15

msgChannel:
  type: 'kafka'

kafka:
  host: '192.168.0.31:9092'
  topic: 'go-msg'

upload:
  staticPath: app/upload/